### ISSUE TITLE
question about second method

### ISSUE THREAD

**Issue by wujy2015** [trinitybest/stocktwits_web_scraping#1]
I saw the script takes the symbol id which is specific id for stock twits. Is there any way to scroll all the stock symbol? I only have symbol names.

**Comment by trinitybest** [comment]
I don't have an easy way to get all the ids yet. So far, I could only get id one by one. 
Here is how I get the id: 
http://deanhu.co.uk.s3-website-ap-southeast-2.amazonaws.com/ST.PNG
